import React, { FormEvent, useEffect, useState } from 'react';
import PageShell from '../../components/PageShell';
import { bookingsAPI, businessesAPI } from '../../services/api';

interface Service { id: string; name: string; description?: string; price?: number; duration_hours?: number; }
interface Booking { id: string; title: string; description?: string; start_date: string; status: string; tourist_first_name?: string; }
export default function Dashboard() {
  const [services, setServices] = useState<Service[]>([]); const [bookings, setBookings] = useState<Booking[]>([]); const [form, setForm] = useState({ name: '', description: '', price: '', duration_hours: '' }); const [state, setState] = useState({ loading: true, error: '', saving: false });
  const load = () => { setState((current) => ({ ...current, loading: true, error: '' })); Promise.all([businessesAPI.getServices(), bookingsAPI.getAll()]).then(([serviceResponse, bookingResponse]) => { setServices(serviceResponse.data.items || []); setBookings(bookingResponse.data.items || []); }).catch(() => setState((current) => ({ ...current, error: 'Could not load business dashboard.' }))).finally(() => setState((current) => ({ ...current, loading: false }))); };
  useEffect(() => { load(); }, []);
  const addService = async (event: FormEvent) => { event.preventDefault(); setState((current) => ({ ...current, saving: true, error: '' })); try { const { data } = await businessesAPI.createService({ ...form, price: form.price ? Number(form.price) : null, duration_hours: form.duration_hours ? Number(form.duration_hours) : null }); setServices((current) => [data, ...current]); setForm({ name: '', description: '', price: '', duration_hours: '' }); } catch { setState((current) => ({ ...current, error: 'Could not add service.' })); } finally { setState((current) => ({ ...current, saving: false })); } };
  const updateBooking = async (id: string, status: string) => { try { const { data } = await bookingsAPI.updateStatus(id, status); setBookings((current) => current.map((item) => item.id === id ? { ...item, ...data } : item)); } catch { setState((current) => ({ ...current, error: 'Could not update request.' })); } };
  return <PageShell title="Business dashboard">{state.loading && <p role="status">Loading dashboard…</p>}{state.error && <div className="mb-4 rounded bg-red-50 p-3 text-red-700">{state.error} <button className="underline" onClick={load}>Retry</button></div>} {!state.loading && <><section className="mb-8"><h2 className="mb-3 text-xl font-semibold">Services</h2><form onSubmit={addService} className="mb-4 grid gap-2 rounded-xl bg-white p-5 shadow md:grid-cols-4"><input className="rounded border px-3 py-2" placeholder="Service name" required value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} /><input className="rounded border px-3 py-2" placeholder="Description" value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} /><input className="rounded border px-3 py-2" type="number" min="0" placeholder="Price" value={form.price} onChange={(event) => setForm({ ...form, price: event.target.value })} /><button disabled={state.saving} className="rounded bg-teal-700 px-3 py-2 text-white">Add service</button></form>{services.length === 0 ? <p className="rounded bg-white p-5 text-slate-600">No services listed yet.</p> : <div className="grid gap-3 md:grid-cols-3">{services.map((service) => <div className="rounded bg-white p-4 shadow" key={service.id}><b>{service.name}</b><p>{service.description}</p>{service.price != null && <p>${service.price}</p>}</div>)}</div>}</section><section><h2 className="mb-3 text-xl font-semibold">Booking requests</h2>{bookings.length === 0 ? <p className="rounded bg-white p-5 text-slate-600">No booking requests yet.</p> : <div className="grid gap-3 md:grid-cols-2">{bookings.map((booking) => <article className="rounded bg-white p-4 shadow" key={booking.id}><b>{booking.title}</b><p className="text-sm">From {booking.tourist_first_name || 'traveler'} · {booking.start_date}</p><p>Status: {booking.status}</p>{booking.status === 'pending' && <div className="mt-2 flex gap-2"><button className="rounded bg-teal-700 px-3 py-2 text-sm text-white" onClick={() => void updateBooking(booking.id, 'confirmed')}>Accept</button><button className="rounded border px-3 py-2 text-sm" onClick={() => void updateBooking(booking.id, 'cancelled')}>Decline</button></div>}</article>)}</div>}</section></>}</PageShell>;
}
