import React, { useEffect, useState } from 'react';
import PageShell from '../../components/PageShell';
import { adminAPI } from '../../services/api';

export default function People() {
  const [users, setUsers] = useState<any[]>([]); const [guides, setGuides] = useState<any[]>([]); const [businesses, setBusinesses] = useState<any[]>([]); const [error, setError] = useState(''); const [loading, setLoading] = useState(true);
  const load = () => { setLoading(true); setError(''); Promise.all([adminAPI.getUsers(), adminAPI.getGuides(), adminAPI.getBusinesses()]).then(([u, g, b]) => { setUsers(u.data.items || []); setGuides(g.data.items || []); setBusinesses(b.data.items || []); }).catch(() => setError('Could not load people management data.')).finally(() => setLoading(false)); };
  useEffect(() => { load(); }, []);
  const toggle = async (user: any) => { try { const { data } = await adminAPI.updateUser(user.id, { is_active: !user.is_active }); setUsers((current) => current.map((item) => item.id === data.id ? data : item)); } catch { setError('Could not update user status.'); } };
  const verify = async (kind: 'guide' | 'business', id: string, status: string) => { try { if (kind === 'guide') { const { data } = await adminAPI.updateGuideVerification(id, status); setGuides((current) => current.map((item) => item.id === id ? { ...item, ...data } : item)); } else { const { data } = await adminAPI.updateBusinessVerification(id, status); setBusinesses((current) => current.map((item) => item.id === id ? { ...item, ...data } : item)); } } catch { setError('Could not update verification status.'); } };
  return <PageShell title="People management">{loading && <p role="status">Loading people…</p>}{error && <p className="mb-4 text-red-600">{error} <button className="underline" onClick={load}>Retry</button></p>}{!loading && <div className="grid gap-6 lg:grid-cols-3"><section className="rounded-xl bg-white p-5 shadow"><h2 className="mb-3 font-semibold">Users</h2>{!users.length && <p className="text-slate-500">No users.</p>}{users.map((user) => <div className="border-b py-3 last:border-0" key={user.id}><p className="font-medium">{user.first_name || user.email}</p><p className="text-xs text-slate-500">{user.role} · {user.is_active ? 'Active' : 'Suspended'}</p><button className="mt-2 text-sm text-teal-700 underline" onClick={() => void toggle(user)}>{user.is_active ? 'Suspend' : 'Reactivate'}</button></div>)}</section><Verification title="Guides" items={guides} onVerify={(id, status) => void verify('guide', id, status)} /><Verification title="Businesses" items={businesses} onVerify={(id, status) => void verify('business', id, status)} /></div>}</PageShell>;
}
function Verification({ title, items, onVerify }: { title: string; items: any[]; onVerify: (id: string, status: string) => void }) { return <section className="rounded-xl bg-white p-5 shadow"><h2 className="mb-3 font-semibold">{title}</h2>{!items.length && <p className="text-slate-500">No profiles.</p>}{items.map((item) => <div className="border-b py-3 last:border-0" key={item.id}><p className="font-medium">{item.business_name || `${item.first_name || ''} ${item.last_name || ''}`.trim() || item.email}</p><p className="text-xs text-slate-500">{item.verification_status}</p><div className="mt-2 flex gap-2"><button className="text-sm text-teal-700 underline" onClick={() => onVerify(item.id, 'verified')}>Verify</button><button className="text-sm text-red-600 underline" onClick={() => onVerify(item.id, 'rejected')}>Reject</button></div></div>)}</section>; }
