import React, { FormEvent, useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import PageShell from '../../components/PageShell';
import { bookingsAPI, businessesAPI } from '../../services/api';

export default function BusinessDetail() {
  const { id } = useParams<{ id: string }>(); const [business, setBusiness] = useState<any>(null); const [form, setForm] = useState({ title: 'Service booking request', description: '', start_date: '', end_date: '', service_id: '', total_cost: '' }); const [state, setState] = useState({ loading: true, submitting: false, error: '', message: '' });
  useEffect(() => { if (id) businessesAPI.getById(id).then(({ data }) => { setBusiness(data); setForm((current) => ({ ...current, service_id: data.services?.[0]?.id || '' })); }).catch(() => setState((current) => ({ ...current, error: 'Could not load this business.' }))).finally(() => setState((current) => ({ ...current, loading: false }))); }, [id]);
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!id) return; setState((current) => ({ ...current, submitting: true, error: '', message: '' })); try { await bookingsAPI.create({ business_id: id, ...form, total_cost: form.total_cost ? Number(form.total_cost) : undefined }); setState((current) => ({ ...current, submitting: false, message: 'Request sent to the business.' })); } catch (error: any) { setState((current) => ({ ...current, submitting: false, error: error.response?.data?.error || 'Could not send request.' })); } };
  return <PageShell title={business?.business_name || 'Business details'}><Link className="text-sm text-teal-700" to="/guides-business">← Back to local experts</Link>{state.loading && <p className="mt-4" role="status">Loading business…</p>}{state.error && <p className="mt-4 text-red-600">{state.error}</p>}{business && <div className="mt-4 grid gap-6 lg:grid-cols-[1fr_1fr]"><article className="rounded-xl bg-white p-6 shadow"><p className="text-teal-700">{business.category || 'Local business'} · {[business.city, business.state].filter(Boolean).join(', ')}</p><p className="mt-4">{business.description || 'This business has not added a description yet.'}</p><h2 className="mt-6 font-semibold">Services</h2>{business.services?.length ? business.services.map((service: any) => <div className="mt-2 rounded border p-3" key={service.id}><b>{service.name}</b><p>{service.description}</p>{service.price != null && <p>${service.price}</p>}</div>) : <p className="mt-2 text-slate-600">No services listed yet.</p>}</article><form onSubmit={submit} className="grid gap-3 rounded-xl bg-white p-6 shadow"><h2 className="font-semibold">Request a service</h2>{business.services?.length > 0 && <select className="rounded border px-3 py-2" value={form.service_id} onChange={(event) => setForm({ ...form, service_id: event.target.value })}>{business.services.map((service: any) => <option value={service.id} key={service.id}>{service.name}</option>)}</select>}<input className="rounded border px-3 py-2" required value={form.title} onChange={(event) => setForm({ ...form, title: event.target.value })} /><textarea className="rounded border px-3 py-2" required minLength={10} placeholder="Tell the business what you need" value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} /><label className="text-sm">Start date<input className="mt-1 block w-full rounded border px-3 py-2" type="date" required value={form.start_date} onChange={(event) => setForm({ ...form, start_date: event.target.value })} /></label><label className="text-sm">End date<input className="mt-1 block w-full rounded border px-3 py-2" type="date" value={form.end_date} onChange={(event) => setForm({ ...form, end_date: event.target.value })} /></label>{state.error && <p className="text-red-600">{state.error}</p>}{state.message && <p className="text-teal-700">{state.message}</p>}<button disabled={state.submitting} className="rounded bg-teal-700 px-4 py-2 text-white disabled:opacity-50">{state.submitting ? 'Sending…' : 'Send request'}</button></form></div>}</PageShell>;
}
