import React, { FormEvent, useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import PageShell from '../../components/PageShell';
import { bookingsAPI, guidesAPI } from '../../services/api';

export default function GuideDetail() {
  const { id } = useParams<{ id: string }>(); const [guide, setGuide] = useState<any>(null); const [form, setForm] = useState({ title: 'Guided experience request', description: '', start_date: '', end_date: '' }); const [state, setState] = useState({ loading: true, submitting: false, error: '', message: '' });
  useEffect(() => { if (id) guidesAPI.getById(id).then(({ data }) => setGuide(data)).catch(() => setState((current) => ({ ...current, error: 'Could not load this guide.' }))).finally(() => setState((current) => ({ ...current, loading: false }))); }, [id]);
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!id) return; setState((current) => ({ ...current, submitting: true, error: '', message: '' })); try { await bookingsAPI.create({ guide_id: id, ...form }); setState((current) => ({ ...current, submitting: false, message: 'Request sent. The guide will review it shortly.' })); } catch (error: any) { setState((current) => ({ ...current, submitting: false, error: error.response?.data?.error || 'Could not send booking request.' })); } };
  return <PageShell title={guide ? `${guide.first_name || ''} ${guide.last_name || ''}`.trim() || 'Guide details' : 'Guide details'}><Link className="text-sm text-teal-700" to="/guides-business">← Back to guides</Link>{state.loading && <p className="mt-4" role="status">Loading guide…</p>}{state.error && <p className="mt-4 text-red-600">{state.error}</p>}{guide && <div className="mt-4 grid gap-6 lg:grid-cols-[1fr_1fr]"><article className="rounded-xl bg-white p-6 shadow"><p className="text-teal-700">{(guide.expertise || []).join(' · ') || 'Local guide'}</p><p className="mt-4 whitespace-pre-wrap">{guide.bio || 'This guide has not added a bio yet.'}</p><p className="mt-4 text-sm text-slate-600">Languages: {(guide.languages || []).join(', ') || 'Not specified'}</p><p className="text-sm text-slate-600">Rate: {guide.hourly_rate ? `$${guide.hourly_rate}/hour` : 'Contact for rate'}</p></article><form onSubmit={submit} className="grid gap-3 rounded-xl bg-white p-6 shadow"><h2 className="font-semibold">Request this guide</h2><input className="rounded border px-3 py-2" required value={form.title} onChange={(event) => setForm({ ...form, title: event.target.value })} placeholder="Request title" /><textarea className="rounded border px-3 py-2" required minLength={10} value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} placeholder="Tell the guide what you need" /><label className="text-sm">Start date<input className="mt-1 block w-full rounded border px-3 py-2" type="date" required value={form.start_date} onChange={(event) => setForm({ ...form, start_date: event.target.value })} /></label><label className="text-sm">End date<input className="mt-1 block w-full rounded border px-3 py-2" type="date" value={form.end_date} onChange={(event) => setForm({ ...form, end_date: event.target.value })} /></label>{state.error && <p className="text-red-600">{state.error}</p>}{state.message && <p className="text-teal-700">{state.message}</p>}<button disabled={state.submitting} className="rounded bg-teal-700 px-4 py-2 text-white disabled:opacity-50">{state.submitting ? 'Sending…' : 'Send request'}</button></form></div>}</PageShell>;
}
