import React, { useCallback, useEffect, useState } from 'react';
import PageShell from '../../components/PageShell';
import { travelServicesAPI } from '../../services/api';

const types = ['flight', 'hotel', 'train', 'bus', 'cab', 'holiday'];
export default function TravelServices() {
  const [type, setType] = useState(''); const [items, setItems] = useState<any[]>([]); const [state, setState] = useState({ loading: true, error: '', message: '' }); const [selected, setSelected] = useState<any>(null); const [date, setDate] = useState('');
  const load = useCallback(() => { setState((current) => ({ ...current, loading: true, error: '' })); return travelServicesAPI.getAll(type ? { type } : undefined).then(({ data }) => setItems(data.items || [])).catch(() => setState((current) => ({ ...current, error: 'Could not load travel services.' }))).finally(() => setState((current) => ({ ...current, loading: false }))); }, [type]);
  useEffect(() => { void load(); }, [load]);
  const reserve = async () => { if (!selected || !date) return; try { await travelServicesAPI.reserve({ service_id: selected.id, title: selected.title, description: `Demo reservation with ${selected.provider_name}`, start_date: date, total_cost: selected.price_from }); setState((current) => ({ ...current, message: 'Reservation request sent.' })); setSelected(null); } catch { setState((current) => ({ ...current, error: 'Could not create reservation.' })); } };
  return <PageShell title="Travel services"><div className="mb-6 flex flex-wrap gap-2"><button className={`rounded px-3 py-2 ${!type ? 'bg-teal-700 text-white' : 'border'}`} onClick={() => setType('')}>All</button>{types.map((value) => <button className={`rounded px-3 py-2 ${type === value ? 'bg-teal-700 text-white' : 'border'}`} key={value} onClick={() => setType(value)}>{value}</button>)}</div>{state.message && <p className="mb-4 text-teal-700">{state.message}</p>}{state.loading && <p role="status">Loading services…</p>}{state.error && <p className="text-red-600">{state.error} <button className="underline" onClick={load}>Retry</button></p>}{!state.loading && !state.error && items.length === 0 && <p className="rounded bg-white p-6 text-slate-600">No services match this category.</p>}<div className="grid gap-4 md:grid-cols-3">{items.map((item) => <article className="rounded-xl bg-white p-5 shadow" key={item.id}><p className="text-xs uppercase text-teal-700">{item.service_type}</p><h2 className="mt-1 font-semibold">{item.title}</h2><p className="text-sm text-slate-500">{item.provider_name} · {item.city}</p><p className="mt-2 text-slate-600">{item.description}</p><p className="mt-3 font-medium">From ₹{item.price_from || '—'}</p><button className="mt-4 rounded bg-teal-700 px-3 py-2 text-sm text-white" onClick={() => setSelected(item)}>Request reservation</button>{item.booking_url && <a className="ml-3 text-sm text-teal-700 underline" href={item.booking_url} target="_blank" rel="noreferrer">Provider site</a>}</article>)}</div>{selected && <div className="fixed inset-0 flex items-center justify-center bg-black/40 p-4"><div className="w-full max-w-md rounded-xl bg-white p-6"><h2 className="text-xl font-semibold">Reserve {selected.title}</h2><label className="mt-4 grid gap-1 text-sm">Start date<input className="rounded border px-3 py-2" type="date" value={date} onChange={(event) => setDate(event.target.value)} /></label><div className="mt-4 flex gap-2"><button className="rounded bg-teal-700 px-4 py-2 text-white" onClick={() => void reserve()}>Send request</button><button className="rounded border px-4 py-2" onClick={() => setSelected(null)}>Cancel</button></div></div></div>}</PageShell>;
}
